### ISSUE TITLE
Somethings wrong

### ISSUE THREAD

**Issue by darkadams** [BumbumKill/RepairRenameUI#9]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Well when I'm in game /repair command dont show it keeps saying unknown command and also the config for repairrenameui was empty .

**Comment by darkadams** [comment]
U closed the issue but I'm still having the same problem what us the
command to repair ur items I already did /repair and nothing shows or works.

**Comment by BumbumKill** [comment]
the command is /rr
